name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_emby_4_6:
    name: Build for emby-4.6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 2.0.x
      
      - name: Install OpenSSL 1.0      
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.9_amd64.deb 
          sudo apt install ./libssl1.0.0_1.0.2n-1ubuntu5.9_amd64.deb
          
      - name: Install dependencies
        run: dotnet restore subbuzz.emby.4.6.csproj
        
      - name: Build for emby-4.6
        run: dotnet build subbuzz.emby.4.6.csproj --configuration Release --no-restore

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-emby-4.6
          if-no-files-found: error
          path: ./bin/emby-4.6/Release/netstandard2.0/subbuzz.dll

  build_emby_4_7:
    name: Build for emby-4.7
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 2.0.x
          
      - name: Install OpenSSL 1.0      
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.9_amd64.deb 
          sudo apt install ./libssl1.0.0_1.0.2n-1ubuntu5.9_amd64.deb
          
      - name: Install dependencies
        run: dotnet restore subbuzz.emby.4.7.csproj
          
      - name: Build for emby-4.7
        run: dotnet build subbuzz.emby.4.7.csproj --configuration Release --no-restore

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-emby-4.6
          if-no-files-found: error
          path: ./bin/emby-4.7/Release/netstandard2.0/subbuzz.dll
          
  build_jellyfin_10_7:
    name: Build for jellyfin-10.7
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove unused files
        run: |
          rm *.sln
          find *.csproj -not -name 'subbuzz.jellyfin.10.7.csproj' -delete
          mv build.jellyfin.10.7.yaml build.yaml
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
          
      - name: Build for jellyfin-10.7
        uses: oddstr13/jellyfin-plugin-repository-manager@v0.4.2
        id: jprm
        with:
          dotnet-target: net5.0
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-jellyfin-10.7
          if-no-files-found: error
          path: ${{ steps.jprm.outputs.artifact }}

  build_jellyfin_10_8:
    name: Build for jellyfin-10.8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Remove unused files
        run: |
          rm *.sln
          find *.csproj -not -name 'subbuzz.jellyfin.10.8.csproj' -delete
          mv build.jellyfin.10.8.yaml build.yaml
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Build for jellyfin-10.8
        uses: oddstr13/jellyfin-plugin-repository-manager@v0.4.2
        id: jprm
        with:
          dotnet-target: net6.0
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-jellyfin-10.8
          if-no-files-found: error
          path: ${{ steps.jprm.outputs.artifact }}
